### PR TITLE
Second fix for out of buffers

### LINKED ISSUE #214: Unable to resize or move windows and share freeze
I am using latest main of hyprland (f8857e6072bd85b95393499688872aaf7f088b5b) and xdg-desktop-portal-hyprland (af7c87a32f5d67eb2ada908a6a700f4e74831943)  to share windows using vivaldi and https://mozilla.github.io/webrtc-landing/gum_test.html (Problem occurs on other apps such as teams or slack too) and I am experiencing the following issues:
- When starting to share a window, I cannot move or resize windows anymore. Even when I stop sharing, I have to create a new window in order to make the keybind for window move and resize to work again
- If, while sharing a window, I create a new window, the stream freezes and I have to restart it again. 

Here are the log of xdg-desktop-portal-hyprland:
```
[LOG] Initializing xdph...
[LOG] XDG_CURRENT_DESKTOP set to Hyprland
[LOG] Gathering exported interfaces
[LOG]  | Got interface: wl_seat (ver 9)
[LOG]  | Got interface: wl_data_device_manager (ver 3)
[LOG]  | Got interface: wp_tearing_control_manager_v1 (ver 1)
[LOG]  | Got interface: wp_fractional_scale_manager_v1 (ver 1)
[LOG]  | Got interface: zxdg_output_manager_v1 (ver 3)
[LOG]  | Got interface: wp_cursor_shape_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_idle_inhibit_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_relative_pointer_manager_v1 (ver 1)
[LOG]  | Got interface: zxdg_decoration_manager_v1 (ver 1)
[LOG]  | Got interface: wp_alpha_modifier_v1 (ver 1)
[LOG]  | Got interface: zwlr_gamma_control_manager_v1 (ver 1)
[LOG]  | Got interface: ext_foreign_toplevel_list_v1 (ver 1)
[LOG]  | Got interface: zwp_pointer_gestures_v1 (ver 3)
[LOG]  | Got interface: zwlr_foreign_toplevel_manager_v1 (ver 3)
[LOG] [toplevel] (activate) locks: 1
[LOG]  | Got interface: zwp_keyboard_shortcuts_inhibit_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_text_input_manager_v3 (ver 1)
[LOG]  | Got interface: zwp_pointer_constraints_v1 (ver 1)
[LOG]  | Got interface: zwlr_output_power_manager_v1 (ver 1)
[LOG]  | Got interface: xdg_activation_v1 (ver 1)
[LOG]  | Got interface: ext_idle_notifier_v1 (ver 1)
[LOG]  | Got interface: ext_session_lock_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_input_method_manager_v2 (ver 1)
[LOG]  | Got interface: zwp_virtual_keyboard_manager_v1 (ver 1)
[LOG]  | Got interface: zwlr_virtual_pointer_manager_v1 (ver 2)
[LOG]  | Got interface: zwlr_output_manager_v1 (ver 4)
[LOG]  | Got interface: org_kde_kwin_server_decoration_manager (ver 1)
[LOG]  | Got interface: hyprland_focus_grab_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_tablet_manager_v2 (ver 1)
[LOG]  | Got interface: zwlr_layer_shell_v1 (ver 5)
[LOG]  | Got interface: wp_presentation (ver 1)
[LOG]  | Got interface: xdg_wm_base (ver 6)
[LOG]  | Got interface: zwlr_data_control_manager_v1 (ver 2)
[LOG]  | Got interface: zwp_primary_selection_device_manager_v1 (ver 1)
[LOG]  | Got interface: hyprland_toplevel_export_manager_v1 (ver 2)
[LOG]  | Got interface: zwp_text_input_manager_v1 (ver 1)
[LOG]  | Got interface: hyprland_global_shortcuts_manager_v1 (ver 1)
[LOG] [globalshortcuts] registered
[LOG]  | Got interface: zwlr_screencopy_manager_v1 (ver 3)
[LOG] [pipewire] connected
[LOG] [screencopy] init successful
[LOG]  | Got interface: wl_shm (ver 1)
[LOG]  | Got interface: wl_drm (ver 2)
[LOG]  | Got interface: zwp_linux_dmabuf_v1 (ver 4)
[LOG]  | Got interface: wl_compositor (ver 6)
[LOG]  | Got interface: wl_subcompositor (ver 1)
[LOG]  | Got interface: wp_viewporter (ver 1)
[LOG]  | Got interface: wp_drm_lease_device_v1 (ver 1)
[LOG]  | Got interface: wp_single_pixel_buffer_manager_v1 (ver 1)
[LOG]  | Got interface: xwayland_shell_v1 (ver 1)
[LOG]  | Got interface: wl_output (ver 4)
[LOG] [core] dmabufFeedbackMainDevice
[LOG] Found output name eDP-1
[LOG] [toplevel] Activated, bound to 16efc30, toplevels: 2
[LOG] [screencopy] Registered for toplevel export
[LOG] [screenshot] init successful
[LOG] [toplevel] (activate) locks: 2
[LOG] [screencopy] New session:
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/request/1_58/webrtc_1756487069
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/session/1_58/webrtc_session520650469
[LOG] [screencopy]  | appid: 
[LOG] [screencopy] SelectSources:
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/request/1_58/webrtc675540929
[LOG] [screencopy]  | /org/freedesktop/portal/desktop/session/1_58/webrtc_session520650469
[LOG] [screencopy]  | appid: 
[LOG] [screencopy] option persist_mode to 1
[LOG] [screencopy] unused option multiple
[LOG] [screencopy] unused option types
[LOG] [screencopy] restore data invalid / missing, prompting
[LOG] execAndGet: WAYLAND_DISPLAY=wayland-1 QT_QPA_PLATFORM="wayland" XCURSOR_SIZE=30 HYPRLAND_INSTANCE_SIGNATURE=f8857e6072bd85b95393499688872aaf7f088b5b_1716109869_1894720746 XDPH_WINDOW_SHARING_LIST="24061008[HC>]vivaldi-stable[HT>]gUM Test Page - Vivaldi[HE>]24256960
```

### PR DESCRIPTION
**Pull request by aacebedo**
Basically applying the fix of #249 and shall fix #214 too

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]

File: src/portals/Screencopy.cpp [hunk 1]
```diff
@@ -271,6 +271,12 @@ static void hlOnBufferDone(void* data, hyprland_toplevel_export_frame_v1* frame)
         PSESSION->sharingData.windowFrameCallback = nullptr;
         Debug::log(LOG, "[screencopy/pipewire] Out of buffers");
         PSESSION->sharingData.status = FRAME_NONE;
+        if (PSESSION->sharingData.copyRetries++ < MAX_RETRIES) {
+            Debug::log(LOG, "[sc] Retrying screencopy ({}/{})", PSESSION->sharingData.copyRetries, MAX_RETRIES);
+            g_pPortalManager->m_sPortals.screencopy->m_pPipewire->updateStreamParam(PSTREAM);
+            g_pPortalManager->m_sPortals.screencopy->queueNextShareFrame(PSESSION);
+        }
+        PSESSION->sharingData.copyRetries = 0;
```
Comment (vaxerski) [inline src/portals/Screencopy.cpp:279]: wait no this is wrong, it should be a few lines below, right before hyprland_toplevel_export_frame_v1_copy

Comment (aacebedo) [reply src/portals/Screencopy.cpp]: My bad. I moved the line 279 where you pointed.

**Review by vaxerski — APPROVED** [review]
