### PR TITLE
global shortcuts: fix crash by ignoring duplicate shortcuts

### LINKED ISSUE #236: Crashes when registering a taken global shortcut id
Instead of just failing to register the shortcut, xdph crashes when a shortcut that is already taken is registered again.

```[LOG] Initializing xdph...
[LOG] XDG_CURRENT_DESKTOP set to Hyprland
[LOG] Gathering exported interfaces
[LOG]  | Got interface: wl_seat (ver 9)
[LOG]  | Got interface: wl_data_device_manager (ver 3)
[LOG]  | Got interface: wl_compositor (ver 6)
[LOG]  | Got interface: wl_subcompositor (ver 1)
[LOG]  | Got interface: wl_shm (ver 1)
[LOG]  | Got interface: wp_viewporter (ver 1)
[LOG]  | Got interface: wp_tearing_control_manager_v1 (ver 1)
[LOG]  | Got interface: wp_fractional_scale_manager_v1 (ver 1)
[LOG]  | Got interface: zxdg_output_manager_v1 (ver 3)
[LOG]  | Got interface: wp_cursor_shape_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_idle_inhibit_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_relative_pointer_manager_v1 (ver 1)
[LOG]  | Got interface: zxdg_decoration_manager_v1 (ver 1)
[LOG]  | Got interface: wp_alpha_modifier_v1 (ver 1)
[LOG]  | Got interface: zwlr_gamma_control_manager_v1 (ver 1)
[LOG]  | Got interface: ext_foreign_toplevel_list_v1 (ver 1)
[LOG]  | Got interface: zwp_pointer_gestures_v1 (ver 3)
[LOG]  | Got interface: zwlr_foreign_toplevel_manager_v1 (ver 3)
[LOG] [toplevel] (activate) locks: 1
[LOG]  | Got interface: zwp_keyboard_shortcuts_inhibit_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_text_input_manager_v3 (ver 1)
[LOG]  | Got interface: zwp_pointer_constraints_v1 (ver 1)
[LOG]  | Got interface: zwlr_output_power_manager_v1 (ver 1)
[LOG]  | Got interface: xdg_activation_v1 (ver 1)
[LOG]  | Got interface: ext_idle_notifier_v1 (ver 1)
[LOG]  | Got interface: ext_session_lock_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_input_method_manager_v2 (ver 1)
[LOG]  | Got interface: zwp_virtual_keyboard_manager_v1 (ver 1)
[LOG]  | Got interface: zwlr_virtual_pointer_manager_v1 (ver 2)
[LOG]  | Got interface: zwlr_output_manager_v1 (ver 4)
[LOG]  | Got interface: org_kde_kwin_server_decoration_manager (ver 1)
[LOG]  | Got interface: hyprland_focus_grab_manager_v1 (ver 1)
[LOG]  | Got interface: zwp_tablet_manager_v2 (ver 1)
[LOG]  | Got interface: zwlr_layer_shell_v1 (ver 5)
[LOG]  | Got interface: wp_presentation (ver 1)
[LOG]  | Got interface: xdg_wm_base (ver 6)
[LOG]  | Got interface: zwlr_data_control_manager_v1 (ver 2)
[LOG]  | Got interface: zwp_primary_selection_device_manager_v1 (ver 1)
[LOG]  | Got interface: xwayland_shell_v1 (ver 1)
[LOG]  | Got interface: wl_drm (ver 2)
[LOG]  | Got interface: zwp_linux_dmabuf_v1 (ver 5)
[LOG]  | Got interface: hyprland_toplevel_export_manager_v1 (ver 2)
[LOG]  | Got interface: zwp_text_input_manager_v1 (ver 1)
[LOG]  | Got interface: hyprland_global_shortcuts_manager_v1 (ver 1)
[LOG] [globalshortcuts] registered
[LOG]  | Got interface: zwlr_screencopy_manager_v1 (ver 3)
[LOG] [pipewire] connected
[LOG] [screencopy] init successful
[LOG]  | Got interface: wp_drm_lease_device_v1 (ver 1)
[LOG]  | Got interface: wl_output (ver 4)
[LOG] [core] dmabufFeedbackMainDevice
[LOG] Found output name eDP-1
[LOG] [toplevel] Activated, bound to 55f5517f35a0, toplevels: 6
[LOG] [screencopy] Registered for toplevel export
[LOG] [screenshot] init successful
[LOG] [globalshortcuts] New session:
[LOG] [globalshortcuts]  | /org/freedesktop/portal/desktop/request/1_84/crash_KvTdjPNNbC
[LOG] [globalshortcuts]  | /org/freedesktop/portal/desktop/session/1_84/crash_lvbVLj6FZZ
[LOG] [globalshortcuts]  | appid: 
[LOG] [globalshortcuts] Bind keys:
[LOG] [globalshortcuts]  | /org/freedesktop/portal/desktop/session/1_84/crash_lvbVLj6FZZ
[LOG] [globalshortcuts] registered 1 shortcuts
[LOG] [globalshortcuts] New session:
[LOG] [globalshortcuts]  | /org/freedesktop/portal/desktop/request/1_85/crash_z6Sznwf2gJ
[LOG] [globalshortcuts]  | /org/freedesktop/portal/desktop/session/1_85/crash_hDRKFgzubO
[LOG] [globalshortcuts]  | appid: 
[LOG] [globalshortcuts] Bind keys:
[LOG] [globalshortcuts]  | /org/freedesktop/portal/desktop/session/1_85/crash_hDRKFgzubO
[LOG] [globalshortcuts] registered 1 shortcuts
hyprland_global_shortcuts_manager_v1@10: error 0: Combination is taken
[CRITICAL] [core] Disconnected from pollfd id 1
[ERR] [core] Terminated
fish: Job 1, '/usr/libexec/xdg-desktop-portal…' terminated by signal SIGSEGV (Address boundary error)
```

### PR DESCRIPTION
**Pull request by dec05eba**
hyprland_global_shortcuts_manager_v1_register_shortcut will cause an error if the (app_id, shortcut_id) combination has already been registered. Ignore shortcuts that have already been registered.

When a shortcut is registered again it should also overwrite the session for the keybind to make the shortcut work after restarting an application, otherwise the key can't be used again.

Fixes #236

### CODE REVIEW

**Comment by dec05eba** [comment]
I also noticed that "shortcuts" in CreateSession will never exist since xdg-desktop-portal ignores that key. This means that to make sure shortcuts work applications need to call BindShortcut on program startup. The issue with that is that BindShortcut documentation says that the portal can show a dialog when this happens (https://github.com/flatpak/xdg-desktop-portal/blob/a74c2ee93befca1f8583e86e165dbe90a0e72a15/data/org.freedesktop.portal.GlobalShortcuts.xml#L88) and that is the case with KDE. It will show the global shortcuts dialog where you can setup keys.
That means you cant call BindShortcut on program startup as that would show the dialog everytime. The only solution I know right now is to only call BindShortcut on program startup if the desktop portal running on the system is Hyprland.

KDE handles this differently. It saves the "session_handle_token" and automatically registers the shortcuts the next time you call CreateSession with the same "session_handle_token".

**Comment by dec05eba** [comment]
(I tested these changes with a real program (https://git.dec05eba.com/gpu-screen-recorder-gtk/about/), after allowing it to run on hyprland)

File: src/portals/GlobalShortcuts.cpp [hunk 1]
```diff
@@ -32,6 +32,50 @@ CGlobalShortcutsPortal::SSession* CGlobalShortcutsPortal::getSession(sdbus::Obje
...
+    return nullptr;
+}
+
+SKeybind* CGlobalShortcutsPortal::registerShortcut(SSession* session, const DBusShortcut& shortcut) {
+    std::string id = shortcut.get<0>();
+    std::unordered_map<std::string, sdbus::Variant> data = shortcut.get<1>();
+    std::string description;
+
+    for (auto& [k, v] : data) {
+        if (k == "description") {
```
Comment (vaxerski) [inline src/portals/GlobalShortcuts.cpp:55]: no {} around short ifs

File: src/portals/GlobalShortcuts.cpp [hunk 2]
```diff
@@ -32,6 +32,50 @@ CGlobalShortcutsPortal::SSession* CGlobalShortcutsPortal::getSession(sdbus::Obje
...
+            description = v.get<std::string>();
+        } else {
+            Debug::log(LOG, "[globalshortcuts] unknown shortcut data type {}", k);
+        }
+    }
+
+    auto* PSHORTCUT = getShortcutById(session->appid, id);
+    if (PSHORTCUT) {
```
Comment (vaxerski) [inline src/portals/GlobalShortcuts.cpp:63]: ditto

File: src/portals/GlobalShortcuts.cpp (hunk 1 above)
Comment (dec05eba) [reply src/portals/GlobalShortcuts.cpp]: done

File: src/portals/GlobalShortcuts.cpp (hunk 2 above)
Comment (dec05eba) [reply src/portals/GlobalShortcuts.cpp]: done

**Review by vaxerski — APPROVED** [review]
thanks!
